name: Update UML diagrams
on:
  pull_request_review:
    types: [submitted]
    branches: development
  workflow_dispatch:

jobs:
  diagrams:
    if: github.event.review.state == 'approved'
    name: Update UML diagrams
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: set up environment
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install icepyx pylint
          sudo apt-get install graphviz
      - name: run pyreverse
        run: |
          pyreverse ./icepyx/core -p user_uml -o svg
          pyreverse ./icepyx/quest -p quest_user_uml -o svg
          pyreverse ./icepyx/core ./icepyx/quest -f ALL -p dev_uml -o svg
          rm ./packages_dev_uml.svg
          mv ./*.svg ./doc/source/user_guide/documentation/
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          message: "GitHub action UML generation auto-update"
          add: "./doc/source/user_guide/documentation/*"
