name: Update UML diagrams
on:
<<<<<<< HEAD
=======
  workflow_dispatch:
>>>>>>> action to automatically update uml diagrams (#208)
  pull_request_review:
    types: [submitted]

jobs:
  diagrams:
    if: github.event.review.state == 'approved'
    name: Update UML diagrams
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: set up environment
        run: |
          pip install -r requirements.txt
          pip install icepyx pylint 
          sudo apt-get install graphviz
      - name: run pyreverse
        run: |
          pyreverse ./icepyx/core -p user_uml -o svg
          pyreverse ./icepyx/core -f ALL -p dev_uml -o svg
          rm ./packages_dev_uml.svg
          mv ./*.svg ./doc/source/user_guide/documentation/
      - name: Commit changes
<<<<<<< HEAD
        uses: EndBug/add-and-commit@v7
=======
        uses: EndBug/add-and-commit@v4
>>>>>>> action to automatically update uml diagrams (#208)
        with:
          author_name: GitHub Action
          message: "GitHub action UML generation auto-update"
          add: "./doc/source/user_guide/documentation/*"
          ref: git branch --show-current
